spring:
  application:
    name: cart-microservice
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgres://postgres:3320/cart
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
