# application-docker.yml
server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update   # nur Dev
